blank_issues_enabled: true
contact_links:
  - name: Security vulnerability
    url: https://github.com/Alien-Worlds/docs/blob/main/SECURITY.md
    about: Please do not report security issues in public issues. See our security policy.
